import type { AiProvider, AiProviderId } from './types';

export const PROVIDERS: Record<AiProviderId, AiProvider> = {
  openai: {
    id: 'openai',
    name: 'OpenAI',
    kind: 'openai-compatible',
    apiKeyLabel: 'OpenAI API key',
    apiKeyHint: 'Starts with sk-… - created at platform.openai.com/api-keys',
    apiKeyUrl: 'https://platform.openai.com/api-keys',
    baseUrl: 'https://api.openai.com/v1/chat/completions',
    badge: 'Pay-per-use',
    notes: 'Separate from ChatGPT Plus. Requires credits at platform.openai.com.',
    models: [
      { id: 'gpt-5', label: 'GPT-5', description: 'Flagship' },
      { id: 'gpt-5-mini', label: 'GPT-5 mini', description: 'Faster + cheaper' },
      { id: 'gpt-5-nano', label: 'GPT-5 nano', description: 'Smallest, fastest' },
      { id: 'o3', label: 'o3', description: 'Reasoning' },
      { id: 'o3-mini', label: 'o3-mini', description: 'Cheaper reasoning' },
      { id: 'o4-mini', label: 'o4-mini', description: 'Latest reasoning' },
      { id: 'gpt-4.1', label: 'GPT-4.1' },
      { id: 'gpt-4.1-mini', label: 'GPT-4.1 mini' },
      { id: 'gpt-4.1-nano', label: 'GPT-4.1 nano' },
      { id: 'gpt-4o', label: 'GPT-4o', description: 'Multimodal' },
      { id: 'gpt-4o-mini', label: 'GPT-4o mini' },
    ],
  },
  anthropic: {
    id: 'anthropic',
    name: 'Anthropic Claude',
    kind: 'anthropic',
    apiKeyLabel: 'Anthropic API key',
    apiKeyHint: 'Starts with sk-ant-… - created at console.anthropic.com',
    apiKeyUrl: 'https://console.anthropic.com/settings/keys',
    badge: 'Pay-per-use',
    notes: 'Separate from Claude Pro. Requires credits at console.anthropic.com.',
    models: [
      { id: 'claude-opus-4-7', label: 'Claude Opus 4.7', description: 'Most capable' },
      { id: 'claude-sonnet-4-6', label: 'Claude Sonnet 4.6', description: 'Best balance' },
      { id: 'claude-haiku-4-5', label: 'Claude Haiku 4.5', description: 'Fastest' },
      { id: 'claude-opus-4-5', label: 'Claude Opus 4.5', description: 'Previous flagship' },
      { id: 'claude-sonnet-4-5', label: 'Claude Sonnet 4.5' },
      { id: 'claude-3-7-sonnet-latest', label: 'Claude 3.7 Sonnet' },
      { id: 'claude-3-5-haiku-latest', label: 'Claude 3.5 Haiku' },
    ],
  },
  gemini: {
    id: 'gemini',
    name: 'Google Gemini',
    kind: 'gemini',
    apiKeyLabel: 'Google AI API key',
    apiKeyHint: 'Created at aistudio.google.com/app/apikey',
    apiKeyUrl: 'https://aistudio.google.com/app/apikey',
    badge: 'Free tier',
    notes: 'Free tier is generous on Flash models; Pro models have tight free limits.',
    models: [
      { id: 'gemini-2.5-pro', label: 'Gemini 2.5 Pro', description: 'Most capable' },
      { id: 'gemini-2.5-flash', label: 'Gemini 2.5 Flash', description: 'Free-tier friendly' },
      { id: 'gemini-2.5-flash-lite', label: 'Gemini 2.5 Flash-Lite' },
      { id: 'gemini-2.0-flash', label: 'Gemini 2.0 Flash' },
      { id: 'gemini-2.0-flash-lite', label: 'Gemini 2.0 Flash-Lite' },
      { id: 'gemini-1.5-pro', label: 'Gemini 1.5 Pro' },
      { id: 'gemini-1.5-flash', label: 'Gemini 1.5 Flash' },
      { id: 'gemini-1.5-flash-8b', label: 'Gemini 1.5 Flash 8B' },
    ],
  },
  groq: {
    id: 'groq',
    name: 'Groq',
    kind: 'openai-compatible',
    apiKeyLabel: 'Groq API key',
    apiKeyHint: 'Starts with gsk_… - created at console.groq.com/keys',
    apiKeyUrl: 'https://console.groq.com/keys',
    baseUrl: 'https://api.groq.com/openai/v1/chat/completions',
    badge: 'Free tier',
    notes: 'Free, very fast inference (sub-second). Per-minute token limits, no daily cap.',
    models: [
      {
        id: 'llama-3.3-70b-versatile',
        label: 'Llama 3.3 70B Versatile',
        description: 'Large, broad',
      },
      { id: 'llama-3.1-8b-instant', label: 'Llama 3.1 8B Instant', description: 'Fastest' },
      { id: 'meta-llama/llama-4-maverick-17b-128e-instruct', label: 'Llama 4 Maverick 17B' },
      { id: 'meta-llama/llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout 17B' },
      { id: 'openai/gpt-oss-120b', label: 'GPT-OSS 120B', description: 'OpenAI open weights' },
      { id: 'openai/gpt-oss-20b', label: 'GPT-OSS 20B' },
      { id: 'qwen/qwen3-32b', label: 'Qwen 3 32B' },
      { id: 'qwen-qwq-32b', label: 'Qwen QwQ 32B', description: 'Reasoning' },
      { id: 'deepseek-r1-distill-llama-70b', label: 'DeepSeek R1 Distill Llama 70B' },
      { id: 'moonshotai/kimi-k2-instruct', label: 'Kimi K2 Instruct' },
      { id: 'mistral-saba-24b', label: 'Mistral Saba 24B' },
    ],
  },
  openrouter: {
    id: 'openrouter',
    name: 'OpenRouter',
    kind: 'openai-compatible',
    apiKeyLabel: 'OpenRouter API key',
    apiKeyHint: 'Starts with sk-or-… - created at openrouter.ai/keys',
    apiKeyUrl: 'https://openrouter.ai/keys',
    baseUrl: 'https://openrouter.ai/api/v1/chat/completions',
    extraHeaders: {
      'HTTP-Referer': 'https://qa-hub.local',
      'X-Title': 'QA Hub',
    },
    badge: 'Free + paid',
    notes:
      'One key, 100+ models. Models with “:free” suffix are free with rate limits; others are pay-per-use.',
    models: [
      // Live list is the source of truth - open the dropdown to fetch all
      // ~300+ models. These are just a static fallback.
      {
        id: 'deepseek/deepseek-r1-0528:free',
        label: 'DeepSeek R1 (free)',
        description: 'Reasoning, free',
      },
      { id: 'deepseek/deepseek-chat-v3-0324:free', label: 'DeepSeek V3 (free)' },
      { id: 'meta-llama/llama-3.3-70b-instruct:free', label: 'Llama 3.3 70B (free)' },
      { id: 'qwen/qwen-2.5-72b-instruct:free', label: 'Qwen 2.5 72B (free)' },
      { id: 'google/gemini-2.0-flash-exp:free', label: 'Gemini 2.0 Flash Exp (free)' },
      { id: 'anthropic/claude-opus-4.7', label: 'Claude Opus 4.7 (paid)' },
      { id: 'anthropic/claude-sonnet-4.6', label: 'Claude Sonnet 4.6 (paid)' },
      { id: 'anthropic/claude-haiku-4.5', label: 'Claude Haiku 4.5 (paid)' },
      { id: 'openai/gpt-5', label: 'GPT-5 (paid)' },
      { id: 'openai/gpt-5-mini', label: 'GPT-5 mini (paid)' },
      { id: 'openai/gpt-4o', label: 'GPT-4o (paid)' },
      { id: 'google/gemini-2.5-pro', label: 'Gemini 2.5 Pro (paid)' },
      { id: 'google/gemini-2.5-flash', label: 'Gemini 2.5 Flash (paid)' },
    ],
  },
  github: {
    id: 'github',
    name: 'GitHub Models',
    kind: 'openai-compatible',
    apiKeyLabel: 'GitHub personal access token',
    apiKeyHint: 'Fine-grained PAT - needs the "Models" read permission',
    apiKeyUrl: 'https://github.com/settings/personal-access-tokens/new',
    baseUrl: 'https://models.github.ai/inference/chat/completions',
    badge: 'Free tier',
    notes:
      'Free for any GitHub user. Rate limits depend on your GitHub plan (Free / Pro / Enterprise).',
    models: [
      { id: 'openai/gpt-5', label: 'GPT-5' },
      { id: 'openai/gpt-5-mini', label: 'GPT-5 mini' },
      { id: 'openai/gpt-5-nano', label: 'GPT-5 nano' },
      { id: 'openai/gpt-4.1', label: 'GPT-4.1' },
      { id: 'openai/gpt-4.1-mini', label: 'GPT-4.1 mini' },
      { id: 'openai/gpt-4o', label: 'GPT-4o' },
      { id: 'openai/gpt-4o-mini', label: 'GPT-4o mini' },
      { id: 'openai/o3', label: 'o3', description: 'Reasoning' },
      { id: 'openai/o3-mini', label: 'o3-mini' },
      { id: 'openai/o4-mini', label: 'o4-mini' },
      { id: 'meta/Llama-3.3-70B-Instruct', label: 'Llama 3.3 70B' },
      { id: 'meta/Llama-4-Maverick-17B-128E-Instruct-FP8', label: 'Llama 4 Maverick' },
      { id: 'meta/Llama-4-Scout-17B-16E-Instruct', label: 'Llama 4 Scout' },
      { id: 'mistral-ai/Mistral-Large-2411', label: 'Mistral Large' },
      { id: 'mistral-ai/Codestral-2501', label: 'Codestral', description: 'Code-tuned' },
      { id: 'microsoft/Phi-4', label: 'Phi-4' },
      { id: 'microsoft/Phi-4-mini-instruct', label: 'Phi-4 mini' },
      { id: 'cohere/Cohere-command-r-plus-08-2024', label: 'Command R+' },
      { id: 'cohere/Cohere-command-a', label: 'Command A' },
      { id: 'deepseek/DeepSeek-R1', label: 'DeepSeek R1', description: 'Reasoning' },
      { id: 'deepseek/DeepSeek-V3-0324', label: 'DeepSeek V3' },
      { id: 'xai/grok-3', label: 'Grok 3' },
      { id: 'xai/grok-3-mini', label: 'Grok 3 mini' },
    ],
  },
  mistral: {
    id: 'mistral',
    name: 'Mistral',
    kind: 'openai-compatible',
    apiKeyLabel: 'Mistral API key',
    apiKeyHint: 'Created at console.mistral.ai',
    apiKeyUrl: 'https://console.mistral.ai/api-keys',
    baseUrl: 'https://api.mistral.ai/v1/chat/completions',
    badge: 'Free tier',
    notes: 'Real free tier on La Plateforme; lower rate limits than the paid plan.',
    models: [
      { id: 'mistral-large-latest', label: 'Mistral Large', description: 'Most capable' },
      { id: 'mistral-medium-latest', label: 'Mistral Medium' },
      { id: 'mistral-small-latest', label: 'Mistral Small', description: 'Free-tier friendly' },
      { id: 'codestral-latest', label: 'Codestral', description: 'Code-tuned' },
      { id: 'ministral-8b-latest', label: 'Ministral 8B' },
      { id: 'ministral-3b-latest', label: 'Ministral 3B' },
      { id: 'magistral-medium-latest', label: 'Magistral Medium', description: 'Reasoning' },
      { id: 'magistral-small-latest', label: 'Magistral Small', description: 'Cheaper reasoning' },
      { id: 'pixtral-large-latest', label: 'Pixtral Large', description: 'Vision' },
      { id: 'open-mistral-nemo', label: 'Mistral Nemo 12B' },
    ],
  },
  cerebras: {
    id: 'cerebras',
    name: 'Cerebras',
    kind: 'openai-compatible',
    apiKeyLabel: 'Cerebras API key',
    apiKeyHint: 'Created at cloud.cerebras.ai',
    apiKeyUrl: 'https://cloud.cerebras.ai/platform/api-keys',
    baseUrl: 'https://api.cerebras.ai/v1/chat/completions',
    badge: 'Free tier',
    notes: 'Fastest inference on the market. Free tier covers Llama / Qwen / GPT-OSS models.',
    models: [
      { id: 'llama-4-scout-17b-16e-instruct', label: 'Llama 4 Scout 17B' },
      { id: 'llama-4-maverick-17b-128e-instruct', label: 'Llama 4 Maverick 17B' },
      { id: 'llama3.3-70b', label: 'Llama 3.3 70B' },
      { id: 'llama-3.1-8b', label: 'Llama 3.1 8B', description: 'Fastest' },
      { id: 'qwen-3-32b', label: 'Qwen 3 32B' },
      { id: 'qwen-3-235b-a22b-instruct-2507', label: 'Qwen 3 235B' },
      { id: 'gpt-oss-120b', label: 'GPT-OSS 120B' },
      { id: 'gpt-oss-20b', label: 'GPT-OSS 20B' },
      { id: 'deepseek-r1-distill-llama-70b', label: 'DeepSeek R1 Distill Llama 70B' },
    ],
  },
  ollama: {
    id: 'ollama',
    name: 'Ollama (local)',
    kind: 'openai-compatible',
    apiKeyLabel: 'Not required',
    apiKeyHint: 'Runs on your machine - no key needed.',
    apiKeyUrl: 'https://ollama.com/download',
    baseUrl: 'http://localhost:11434/v1/chat/completions',
    requiresKey: false,
    badge: 'Local',
    notes:
      'Fully free, fully local. Requires Ollama running and the env var OLLAMA_ORIGINS="*" (or this site\'s origin) so the browser can reach it.',
    models: [
      { id: 'llama3.3', label: 'Llama 3.3 (8B / 70B - depends on what you pulled)' },
      { id: 'llama3.2', label: 'Llama 3.2' },
      { id: 'llama3.1', label: 'Llama 3.1' },
      { id: 'qwen3', label: 'Qwen 3' },
      { id: 'qwen2.5', label: 'Qwen 2.5' },
      { id: 'qwen2.5-coder', label: 'Qwen 2.5 Coder' },
      { id: 'deepseek-r1', label: 'DeepSeek R1', description: 'Reasoning' },
      { id: 'deepseek-v3', label: 'DeepSeek V3' },
      { id: 'mistral', label: 'Mistral 7B' },
      { id: 'mistral-nemo', label: 'Mistral Nemo 12B' },
      { id: 'phi4', label: 'Phi-4' },
      { id: 'phi4-mini', label: 'Phi-4 mini' },
      { id: 'gemma3', label: 'Gemma 3' },
      { id: 'codellama', label: 'Code Llama' },
    ],
  },
};

export const PROVIDER_IDS: AiProviderId[] = [
  'openai',
  'anthropic',
  'gemini',
  'groq',
  'openrouter',
  'github',
  'mistral',
  'cerebras',
  'ollama',
];

export function getProvider(id: AiProviderId): AiProvider {
  return PROVIDERS[id];
}
